# Generated by Django 5.2.6 on 2025-09-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_condominio', '0001_initial'),
        ('residencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExpensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_expensa',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_pago',
            },
        ),
        migrations.CreateModel(
            name='ExpensaVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.vivienda')),
            ],
            options={
                'db_table': 'expensa_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.PositiveBigIntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_pago.factura')),
            ],
            options={
                'db_table': 'detalle_factura',
            },
        ),
        migrations.CreateModel(
            name='NotaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('monto_alquiler', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_otros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('Inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.inquilino')),
            ],
            options={
                'db_table': 'nota_alquiler',
            },
        ),
        migrations.CreateModel(
            name='ServicioBasico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('numero_Factura', models.PositiveBigIntegerField()),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='servicio_basico_images/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.vivienda')),
            ],
            options={
                'db_table': 'servicio_basico',
            },
        ),
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_condominio.condominio')),
                ('tipo_expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_pago.tipoexpensa')),
            ],
            options={
                'db_table': 'expensa',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicio_pago.factura')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_pago.tipopago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
