from .inquilino import InquilinoViewSet,MascotaViewSet,OcupanteViewSet
from .propietario import PropietarioViewSet,ParqueoViewSet,NumeroParqueoViewSet
from .vivienda import ViviendaViewSet,HistorialDueñoViewSet,ContratoViewSet