from .inquilino import InquilinoViewSet,MascotaViewSet,OcupanteViewSet,ContratoViewSet
from .propietario import PropietarioViewSet,ParqueoViewSet,NumeroParqueoViewSet
from .vivienda import ViviendaViewSet,HistorialDueñoViewSet,PropietarioViviendaViewSet
