from .inquilino import InquilinoViewSet,MascotaViewSet
from .propietario import PropietarioViewSet,ParqueoViewSet,NumeroParqueoViewSet
from .vivienda import ViviendaViewSet,HistorialDueñoViewSet,ContratoViewSet