# Generated by Django 5.2.6 on 2025-09-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_condominio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'parqueo',
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inquilino',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(null=True)),
                ('fecha_salida', models.DateTimeField(null=True)),
                ('porcentaje_expensa', models.PositiveSmallIntegerField(null=True)),
                ('tipo_renta', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
                ('inquilino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencias.inquilino')),
            ],
            options={
                'db_table': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='residencias.inquilino')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='Ocupante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_ci', models.PositiveBigIntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupantes', to='residencias.contrato')),
            ],
            options={
                'db_table': 'ocupante',
            },
        ),
        migrations.CreateModel(
            name='NumeroParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquilino_id', models.PositiveBigIntegerField(null=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('parqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.parqueo')),
            ],
            options={
                'db_table': 'numero_parqueo',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_compra', models.DateField()),
                ('QRpago', models.ImageField(null=True, upload_to='qrpago/')),
                ('created_app', models.DateTimeField(auto_now_add=True)),
                ('updated_app', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'propietario',
            },
        ),
        migrations.AddField(
            model_name='parqueo',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residencias.propietario'),
        ),
        migrations.CreateModel(
            name='PropietarioVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.propietario')),
            ],
            options={
                'db_table': 'propietario_vivienda',
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vivienda', models.PositiveSmallIntegerField()),
                ('precio_alquiler', models.PositiveBigIntegerField(null=True)),
                ('precio_anticretico', models.PositiveBigIntegerField(null=True)),
                ('superficie', models.PositiveBigIntegerField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('foto', models.ImageField(null=True, upload_to='vivienda/')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='admin_condominio.condominio')),
                ('propietario', models.ManyToManyField(through='residencias.PropietarioVivienda', to='residencias.propietario')),
            ],
            options={
                'db_table': 'vivienda',
            },
        ),
        migrations.AddField(
            model_name='propietariovivienda',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.vivienda'),
        ),
        migrations.CreateModel(
            name='HistorialDueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('propietario_id', models.PositiveBigIntegerField()),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_dueños', to='residencias.vivienda')),
            ],
            options={
                'db_table': 'historial_dueño',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.vivienda'),
        ),
        migrations.AlterUniqueTogether(
            name='propietariovivienda',
            unique_together={('propietario', 'vivienda')},
        ),
    ]
