# Generated by Django 5.2.6 on 2025-09-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencias.inquilino'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencias.vivienda'),
        ),
    ]
