# Generated by Django 5.2.6 on 2025-09-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquilino',
            name='contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='residencias.inquilino'),
        ),
    ]
