# Generated by Django 5.2.6 on 2025-09-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residencias', '0003_alter_contrato_inquilino_alter_contrato_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
