# Generated by Django 5.2.6 on 2025-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='usuario.RolUsuario', to='usuario.rol'),
        ),
    ]
