# Generated by Django 5.2.6 on 2025-10-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_seeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='face_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
